### ISSUE TITLE
WP-Filebase Error: Could not include class file 'CCron'!

### ISSUE THREAD

**Issue by wcanermaster** [f4bsch/WP-Filebase#21]
After updating the wordpress to new version 4.4.1, the wp-cron file was changed and there has occured a problem on crons. When i run the link 'http://www.website.com/wp-cron.php?doing_wp_cron', the problem 'WP-Filebase Error: Could not include class file 'CCron'!' has been appaired. Thus, my wordpress and other apps using cron do not work properly. 

I have find the new rows which are 
''if (defined('DOING_CRON') && DOING_CRON) {
			wpfb_loadclass('CCron');
			WPFB_CCron::SetLogFile(self::GetLogFile('ccron'));
			WPFB_CCron::doCron($_GET);
		}"
 added on WP-cron and probably causing the problem.

**Comment by clickwork-git** [comment]
Same here.

**Comment by clickwork-git** [comment]
Same or similar here.

The file CCron.php /wp-filebase/classes is missing.

**Comment by f4bsch** [comment]
Has been fixed. https://github.com/f4bsch/WP-Filebase/commit/5ffbfeaa9dbee07466bfeb912b73f44cd6453c9e#diff-1b9a7c8734bc52a00c418e7723d78a83L107

**Comment by wcanermaster** [comment]
Thanks for fast response! Great job..
