### ISSUE TITLE
Icons in Filebrowser have incorrect url

### ISSUE THREAD

**Issue by ReinoutStevens** [f4bsch/WP-Filebase#3]
The url generated for the icons in the filebrowser is incorrect:
http://example.com/wp-content/usr/share/wordpress/wp-content/plugins/wp-filebase/images/folder-icons/folder_cyan48.png

The expected url that actually works would be:
http://example.com/wp-content/plugins/wp-filebase/images/folder-icons/folder_cyan48.png

My site is located in /var/www/example.com/, which is symlinked to /usr/share/wordpress (and somewhere the plugin probably asks for an absolute url).

**Comment by f4bsch** [comment]
This should be fixed. If not, please re-open.
