### ISSUE TITLE
WP-Filebase download account grossly affected by Download Managers

### ISSUE THREAD

**Issue by scarygliders** [f4bsch/WP-Filebase#30]
WP-Filebase appears to be counting each of a multi-part download caused by people using a Download Manager, as individual downloads.

Example: The download count for an application installer from my site was at around 2100, then overnight registered as >4000. After investigating my server logs, I found that the 16MB installer was being downloaded over a time period of 3 hours using >2000 download sessions each with "FDM 3.x" in the header (which I believe is "Free Download Manager 3.x", using HTTP-Range to download..

Unfortunately, de-selecting the Send HTTP-Range header option will cause trouble for some web browsers when attempting to download this small file :)

It would be awesome if there was some way of dealing with this other than outright disabling "Send HTTP-Range header".

Regards

**Comment by f4bsch** [comment]
Thats true, it counts every connection. On not-so-busy-sites it only counts consecutive downloads from the same IP once. There is only one IP field for each field though, so this breaks on busy sites.

I'll change this by only counting downloads starting at byte offset 0.

No idea were the "FDM" header comes from

**Comment by scarygliders** [comment]
Awesome!

"FDM" really does come from "Free Download Manager 3.x" (I was analysing the nginx logs for that particular facepalm-inducing download episode) ;)

Regards

**Comment by f4bsch** [comment]
Ah ok, though it was a header the server itself sent out ;)

**Comment by f4bsch** [comment]
I fixed it by ignoring HEAD requests and those who have the range header not starting at first byte.
