### ISSUE TITLE
classes/item.php line 135 - condition fails - false >=0 - prevents (at least) category sorting

### ISSUE THREAD

**Issue by Obliquely** [f4bsch/WP-Filebase#35]
In classes/item.phpline 135, you are testing the result of strpos($order_sql, ',') by using >=0. When strpos returns false, the test succeeds, and the first character of $order_sql is removed. The error occurs if, for example, you have sortcats="cat_order" in a shortcode. Replacing the line with the following, prevents various warnings being issued and also makes the sort work again:
if ($p !== false && $p >= 0)

**Comment by f4bsch** [comment]
You are right. ```if ($p !== false)``` will do it too. Will fix this with next update.
Thanks!
