### ISSUE TITLE
What can we do???

### ISSUE THREAD

**Issue by Kalusha100** [f4bsch/WP-Filebase#53]
So wp-filebase is not supported any more I think. 
I have a huge Database with this Plugin with over 2000 Files.
Is it possible to change "easy" to another Plugin??? Or do you think it will be supported anytime???

Hope anybody is here and can help me

best regards from Germany :)

**Comment by jeremyflint** [comment]
Hoping to get some info about migrating to another plugin as well.

**Comment by Kalusha100** [comment]
Yes, I hope it too, but I have searched for it and nothing found.  When you hear anything you can write it here :)

**Comment by fl4p** [comment]
Please get latest version at https://github.com/f4bsch/WP-Filebase/archive/master.zip
